# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
dist: trusty
#cache: packages

os:
  - linux
  - osx

r_packages:
  - devtools
  
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libmagick++-dev
